
services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  ai:
    build: 
      context: ./src/backend/ai
      dockerfile: Dockerfile.groq
    ports:
      - "5000:5000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: game_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
