
services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    depends_on:
       db:
        condition: service_healthy
    env_file:
      - .env

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  ai:
    build: 
      context: ./src/backend/ai
      dockerfile: Dockerfile.groq
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: game_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME" ]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 30s


volumes:
  pgdata:
