FROM golang:latest

WORKDIR /app/api-server

# Copy go.mod and go.sum to download dependencies
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy the rest of the app files
COPY api-server .

# Build the Go application
RUN go build -o main .

# Expose the backend port
EXPOSE 8080

# Run the app
CMD ["/app/api-server/main"]