# Use node as a base image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json package-lock.json ./
RUN npm install svelte --save

# Copy the rest of the frontend code
COPY . .

# Build the frontend
RUN npm run build

# Expose the port
EXPOSE 5173

# Serve frontend using a lightweight server
CMD ["npm","run","dev","--", "--host", "--port", "3000"]
